### ISSUE TITLE
Cannot install `requires "nim >= 1.6.5"`

### ISSUE THREAD

**Issue by enthus1ast** [Patitotective/downit#1]
Downit cannot be installed normally, because you use a devel
version in the requirements.

I just cloned it and changed the version to:
requires "nim >= 1.6.4"
and it works fine (through ImThemes)

**Comment by Patitotective** [comment]
Woops, you are right. I forgot to push devel changes to main (new downit version v0.2.1).
Please retry it now and let me know if it works.
(I don't think changing `nim >= 1.6.4` is the right solution if I understand the problem correctly.)

**Comment by enthus1ast** [comment]
No it does not work, 
`Error: Unsatisfied dependency: nim (>= 1.6.5)`
which is true, since i use 
`Nim Compiler Version 1.6.4 [Windows: amd64]`

but its running fine on 1.6.4 thats the reason i proposed to lower the requirements.

This issue hinders the installation of ImThemes on 1.6.4 btw

What i meant with devel version is, the uneven version number, 1.6.**5** this is not a _real_ release. oldstable: 1.6.4 and 1.6.6 the new stable.

**Comment by Patitotective** [comment]
Merged and released in [v0.2.2](https://github.com/Patitotective/downit/releases/tag/0.2.2)
