### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by firasuke** [Patitotective/downit#3]
Hey there,

I appreciate your work on `downit`, but I got some questions:

1- Would it be possible to pair a progress bar (e.g. `suru`) or something else with `downit`?
2- Is there a way to break out of the update loop when all downloads have finished successfully instead of check for them manually? something like `isAllFinished()`?

Thanks again.

**Comment by Patitotective** [comment]
Sorry for the late response.
1. To use suru you need to access `onProgressChanged` which currently is not accesible, this might help you https://github.com/rominf/nim-downloader/blob/main/src/downloader.nim.
2. Here's a workaround:
```nim
import std/[sequtils, tables]
import downit


var downloader = initDownloader("./docs")
downloader.download("https://nim-lang.org/docs/os.html")
downloader.request("https://nim-lang.org/docs/strformat.html")


while true:
  downloader.update() # Poll events and check if downloads are complete


  if downloader.downTable.keys.toSeq.allIt(downloader.succeed(it)):
    echo "succeed all"
    break
```
